PREFIX schema: <https://schema.org/>

SELECT ?recipe ?ingredient
WHERE {
  ?recipe a schema:Recipe ;
          schema:recipeIngredient ?ingredient .
  FILTER(REGEX(STR(?ingredient), "^[ \\t]*1\\s+\\S+s\\b", "i"))
}
