PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <https://schema.org/>

SELECT ?property ?valueCount (?totalEntities - ?valueCount AS ?missingCount)
WHERE {
    	{
        	SELECT (COUNT(DISTINCT ?s) AS ?totalEntities)
        	WHERE { 
				?s rdf:type schema:Recipe. 
				}
    	}
	{
		SELECT ?property (COUNT(DISTINCT ?s) AS ?valueCount)
		WHERE { 
			?s rdf:type schema:Recipe ;
				?property ?o . 
			}
		GROUP BY ?property
	}
}
ORDER BY ASC(?valueCount)