PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <https://schema.org/>

SELECT ?recipe ?cookTime ?prepTime
WHERE {
  ?recipe a schema:Recipe .
  OPTIONAL { ?recipe schema:cookTime ?cookTime . }
  OPTIONAL { ?recipe schema:prepTime ?prepTime . }
  FILTER(
    (bound(?cookTime) && (?cookTime < "PT1M"^^xsd:duration || ?cookTime > "PT720M"^^xsd:duration))
    ||
    (bound(?prepTime) && (?prepTime < "PT1M"^^xsd:duration || ?prepTime > "PT720M"^^xsd:duration))
  )
}
